# Generated by Django 5.1 on 2025-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email_from', models.EmailField(max_length=254)),
                ('email_subject', models.TextField()),
                ('pdf_name', models.CharField(max_length=255)),
                ('case_number', models.IntegerField()),
                ('case_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('api_success', models.BooleanField(default=False)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_automation_processed',
                'ordering': ['-processed_at'],
            },
        ),
    ]
