# Generated by Django 5.2.6 on 2025-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnautomation',
            name='case_type',
            field=models.CharField(choices=[('one_to_one', 'One to One'), ('one_to_many', 'One to Many'), ('many_to_many', 'Many to Many')], default='one_to_one', max_length=20),
        ),
    ]
