# Generated by Django 5.2.6 on 2025-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn_automation', '0002_grnautomation_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationstep',
            name='step_name',
            field=models.CharField(choices=[('upload', 'Upload'), ('sap_login', 'SAP Login'), ('extraction', 'Extraction'), ('grn_details', 'GRN Details'), ('fetch_vendor_code', 'Fetch Vendor Code'), ('fetch_open_grn', 'Fetch Open GRN'), ('filter_grn', 'Filter GRN'), ('validation', 'Validation'), ('booked', 'Booked')], max_length=100),
        ),
        migrations.AlterField(
            model_name='grnautomation',
            name='case_type',
            field=models.CharField(choices=[('one_to_one', 'One to One'), ('one_to_many', 'One to Many'), ('many_to_many', 'Many to Many')], max_length=20, null=True),
        ),
    ]
