# Generated by Django 5.2.6 on 2025-09-29 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn_automation', '0003_alter_automationstep_step_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grnautomation',
            index=models.Index(fields=['created_at'], name='grn_automat_created_e53925_idx'),
        ),
        migrations.AddIndex(
            model_name='grnautomation',
            index=models.Index(fields=['status'], name='grn_automat_status_41b0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='grnautomation',
            index=models.Index(fields=['case_type'], name='grn_automat_case_ty_0ff74c_idx'),
        ),
    ]
