# Generated by Django 5.2.6 on 2025-10-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn_automation', '0004_grnautomation_grn_automat_created_e53925_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationstep',
            options={},
        ),
    ]
