# Generated by Django 5.2.6 on 2025-10-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn_automation', '0005_alter_automationstep_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnautomation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='grnautomation',
            name='validation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('validation_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('card_code', models.CharField(max_length=100)),
                ('doc_entry', models.IntegerField()),
                ('doc_date', models.DateField()),
                ('bpl_id', models.IntegerField()),
                ('posting_status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('posting_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='grn_automation.grnautomation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField()),
                ('remaining_open_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('validation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_lines', to='grn_automation.validationresult')),
            ],
            options={
                'ordering': ['line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['automation', 'invoice_date'], name='grn_automat_automat_bdb279_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['posting_status'], name='grn_automat_posting_d4187d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentline',
            index=models.Index(fields=['validation_result', 'line_num'], name='grn_automat_validat_9e7179_idx'),
        ),
    ]
